# Generated by Django 3.2.7 on 2021-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favorite_fruit', models.CharField(max_length=50)),
                ('favorite_color', models.CharField(max_length=50)),
            ],
        ),
    ]
