# Generated by Django 3.2.7 on 2021-09-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='lab02_app.author'),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('checkout', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='checkout time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab02_app.book')),
            ],
        ),
    ]
