# Generated by Django 3.2.7 on 2021-09-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_app', '0002_auto_20210913_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='lab02_app.book'),
        ),
    ]
