# Generated by Django 3.2.7 on 2021-09-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='book',
        ),
    ]
