# Generated by Django 3.2.7 on 2021-09-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_bought', models.DateTimeField(blank=True, null=True, verbose_name='Date bought')),
                ('bought', models.BooleanField(default=False, verbose_name='Bought?')),
            ],
        ),
    ]
