# Generated by Django 3.2.7 on 2021-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doggo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('temperament', models.CharField(choices=[('aggresive', 'aggresive'), ('lazy', 'lazy'), ('shy', 'shy'), ('nervous', 'nervous'), ('psycho', 'psycho'), ('friendly', 'friendly')], default='friendly', max_length=50)),
                ('bio', models.TextField()),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
