# Generated by Django 3.2.7 on 2021-09-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0004_alter_doggo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doggo',
            name='owner',
        ),
    ]
