# Generated by Django 3.2.7 on 2021-09-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20210916_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
