# Generated by Django 3.2.7 on 2021-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='photo',
            field=models.URLField(default='https://images.dog.ceo/breeds/australian-shepherd/leroy.jpg'),
            preserve_default=False,
        ),
    ]
