# Generated by Django 3.2.7 on 2021-09-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0003_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daycare.owner'),
        ),
    ]
