# Generated by Django 3.2.7 on 2021-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0006_doggo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(default='(123)456-7890', max_length=15),
            preserve_default=False,
        ),
    ]
