# Generated by Django 3.2.7 on 2021-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0002_auto_20210908_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
