# Generated by Django 3.2.7 on 2021-09-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('words', models.CharField(max_length=150)),
                ('sigil_photo', models.URLField()),
                ('sigil_description', models.CharField(max_length=150)),
                ('castle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.location')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='wiki.house')),
            ],
        ),
    ]
