# Generated by Django 3.2.7 on 2021-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20210913_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='characters_who_visited_it',
            field=models.ManyToManyField(related_name='locations', to='wiki.Character'),
        ),
    ]
