# Generated by Django 3.2.7 on 2021-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.DateField(default='2021-09-09'),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created',
            field=models.DateField(default='2021-09-09'),
        ),
    ]
