# Generated by Django 3.2.7 on 2021-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210909_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='created',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(default='2021-09-09'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
