# Generated by Django 3.2.7 on 2021-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_groceryitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='incomplete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
