# Generated by Django 3.2.7 on 2021-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_groceryitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='incomplete',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
