# Generated by Django 3.2.7 on 2021-09-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab03_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('chirp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirp_comment', to='lab03_app.chirp')),
            ],
        ),
    ]
