# Generated by Django 3.2.7 on 2021-09-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab03_app', '0002_chirp_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp_comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users_comment', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chirp_comments',
            name='chirp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='lab03_app.chirp'),
        ),
    ]
