# Generated by Django 3.2.7 on 2021-09-17 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab03_app', '0003_auto_20210917_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
