# Generated by Django 3.2.7 on 2021-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='creation_date',
            new_name='creat_date',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='comp_date',
            field=models.DateTimeField(verbose_name='date completed'),
        ),
    ]
