# Generated by Django 3.2.7 on 2021-09-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_auto_20210909_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
