# Generated by Django 3.2.7 on 2021-09-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_alter_groceryitem_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='comp_date',
            new_name='completion',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='creat_date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='list_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='list_title',
            new_name='title',
        ),
    ]
