# Generated by Django 3.2.7 on 2021-09-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_auto_20210910_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
