# Generated by Django 3.2.7 on 2021-09-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0005_auto_20210913_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
