# Generated by Django 3.2.7 on 2021-09-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0006_alter_groceryitem_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='text',
        ),
    ]
