# Generated by Django 3.2.7 on 2021-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_user_posts_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
