# Generated by Django 3.2.7 on 2021-09-16 18:38

import Lib_App.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('pen_name', models.CharField(max_length=81, verbose_name='Pen Name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('publisher', models.CharField(max_length=40, verbose_name='Publisher')),
                ('pubdate', models.DateField(verbose_name='Date Published')),
                ('author', models.ManyToManyField(related_name='title', to='Lib_App.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('date_out', models.DateField(default=datetime.datetime(2021, 9, 16, 11, 38, 0, 264655), verbose_name='Date Checkout Out')),
                ('due', models.DateField(default=Lib_App.models.get_due_date, verbose_name='Due Date')),
                ('title', models.ManyToManyField(related_name='state', to='Lib_App.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='title', to='Lib_App.Genre'),
        ),
    ]
