# Generated by Django 3.2.7 on 2021-09-15 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='date_out',
            field=models.DateField(default=datetime.datetime(2021, 9, 15, 14, 49, 6, 835538), verbose_name='Date Checkout Out'),
        ),
    ]
