# Generated by Django 3.2.7 on 2021-09-16 22:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lib_App', '0003_alter_tracking_date_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AddField(
            model_name='tracking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Patron', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='date_out',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 15, 15, 13, 737698), verbose_name='Date Checkout Out'),
        ),
    ]
