# Generated by Django 3.2.7 on 2021-09-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
