# Generated by Django 3.2.7 on 2021-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Grocery Item')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_bought', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Bought')),
                ('cleared', models.BooleanField(default=False, verbose_name='Was Purchased')),
            ],
        ),
    ]
