# Generated by Django 3.2.7 on 2021-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceries',
            name='date_bought',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Bought'),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='cleared',
            field=models.BooleanField(default=False, verbose_name='Added?'),
        ),
    ]
