# Generated by Django 3.2.7 on 2021-09-14 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_groceries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
