# Generated by Django 3.2.7 on 2021-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_groceries_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='cleared',
            field=models.BooleanField(default=False, verbose_name='Was Purchased'),
        ),
    ]
