# Generated by Django 3.2.7 on 2021-09-20 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_groceries_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceries',
            name='badid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
