# Generated by Django 3.2.7 on 2021-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_groceries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='cleared',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='date_bought',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Bought'),
        ),
    ]
