# Generated by Django 3.2.7 on 2021-09-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210920_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceries',
            name='badid',
        ),
    ]
