# Generated by Django 3.2.7 on 2021-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='castle',
        ),
        migrations.AddField(
            model_name='character',
            name='locations_visited',
            field=models.ManyToManyField(related_name='characters', to='wiki.Location'),
        ),
    ]
